version: '3.1'

services:

  mongo_db:
    container_name: mongo_db
    image: mongo
    restart: always
    networks: #here
            - mongo_db-network
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
      ME_CONFIG_MONGODB_URL: mongodb://mongo_db:27017/
    networks: #here
            - mongo_db-network
networks: #here
        mongo_db-network:
            driver: bridge